"""Added deltas table

Revision ID: 14a1209d1fe1
Revises: 
Create Date: 2023-11-12 12:36:34.167614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.delta_service.models.db.tables import Delta


# revision identifiers, used by Alembic.
revision: str = '14a1209d1fe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DELTA_LAG_VIEW_NAME = "deltalag"
DELTA_TABLE_NAME = Delta.__tablename__


def create_delta_lag_view() -> None:
    """
    Создание представления для просмотра данных таблицы delta с лагом
    """

    op.execute(
        f"""
        CREATE VIEW {DELTA_LAG_VIEW_NAME}
        AS
        SELECT
            rep_dt,
            delta,
            LAG(delta, -2) OVER (ORDER BY rep_dt) AS DeltaLag
        FROM 
            {DELTA_TABLE_NAME};
        """
    )


def drop_delta_lag_view() -> None:
    """Удаление представления delta с лагом"""

    op.execute(
        f"""
        DROP VIEW IF EXISTS {DELTA_LAG_VIEW_NAME}
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deltas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rep_dt', sa.Date(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    create_delta_lag_view()


def downgrade() -> None:
    drop_delta_lag_view()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deltas')
    # ### end Alembic commands ###
