"""Added deltas table

Revision ID: 14a1209d1fe1
Revises: 
Create Date: 2023-11-12 12:36:34.167614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a1209d1fe1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deltas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rep_dt', sa.Date(), nullable=False),
    sa.Column('delta', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # TODO Create view here


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deltas')
    # ### end Alembic commands ###
    # TODO Create view here
